name: Build and Push to ECR

on:
  push:
    branches: [main]
    paths:
      - 'api/**'
      - 'client/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push API Image
        run: |
          cd api
          docker build -t api:$GITHUB_SHA .
          docker tag api:$GITHUB_SHA ${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_API_REPOSITORY }}:$GITHUB_SHA
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_API_REPOSITORY }}:$GITHUB_SHA

      - name: Build and Push Client Image
        run: |
          cd client
          docker build -t client:$GITHUB_SHA .
          docker tag client:$GITHUB_SHA ${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_CLIENT_REPOSITORY }}:$GITHUB_SHA
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_CLIENT_REPOSITORY }}:$GITHUB_SHA
